name: Publish @daily-co/daily-vcs-web

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Check version changes
        id: version_changes
        run: |
          PREVIOUS_VERSION=$(git show ${{ github.event.before }}:package.json | jq -r '.version')
          CURRENT_VERSION=$(jq -r '.version' package.json)
          echo "PREVIOUS_VERSION=$PREVIOUS_VERSION" >> $GITHUB_ENV
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
          test "$PREVIOUS_VERSION" != "$CURRENT_VERSION"

      - name: Publish to npm
        if: steps.version_changes.outputs.status == '0'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
