name: Publish @daily-co/daily-vcs-web

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Check version changes
        id: version_changes
        run: echo ::set-output name=version::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} package.json)

      - name: Publish to npm
        if: steps.version_changes.outputs.version != ''
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
